# Generated by Django 4.1 on 2022-08-21 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_description", models.CharField(max_length=255)),
                ("item_type", models.CharField(max_length=90)),
                ("item_price", models.CharField(max_length=15)),
                ("item_code", models.CharField(max_length=15)),
                ("expiry", models.DateField()),
                ("quantity_in", models.BigIntegerField(default=0)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.manufacturer",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.pharmacist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
