# Generated by Django 4.1 on 2022-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_quantity",
            field=models.BigIntegerField(default=1),
        ),
    ]
