# Generated by Django 4.1 on 2022-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_inventory_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="item_price",
            field=models.IntegerField(default=0),
        ),
    ]
